### ISSUE TITLE
Is this code safe?

### ISSUE THREAD

**Issue by alimousavi71** [danielroe/nuxt-time#255]
### 🐛 The bug

Considering dom manipulation and changes in dom won't disrupt v-dom?

### 🛠️ To reproduce

https://stackblitz.com/github/danielroe/nuxt-time/tree/main/playground

### 🌈 Expected behaviour

read code

**Comment by danielroe** [comment]
Yes, it's safe! The module exists to ensure there aren't issues with Vue.
