### ISSUE TITLE
minify/transpile script injection at build-time

### ISSUE THREAD

**Issue by danielroe** [danielroe/nuxt-time#3]

**Comment by algora-pbc** [comment]
💎 **$5** bounty created by **danielroe**
🙋 If you start working on this, comment `/attempt #3` along with your implementation plan
👉 To claim this bounty, submit a pull request that includes the text `/claim #3` somewhere in its body
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to danielroe/nuxt-time!

👉 **[Add a bounty](https://console.algora.io/org/danielroe/bounties/community?fund=danielroe%2Fnuxt-time%233)** • **[Share on socials](https://twitter.com/intent/tweet?text=%245+bounty%21+%F0%9F%92%8E+https%3A%2F%2Fgithub.com%2Fdanielroe%2Fnuxt-time%2Fissues%2F3&related=algoraio)**

<table>
<thead>
<tr>
<th>Attempt</th>
<th>Started (GMT+0)</th>
<th>Solution</th>
</tr>
</thead>
<tbody>
<tr>
<td>🟢 @Vijaykv5</td>
<td>Mar 9, 2024, 11:26:13 AM</td>
<td><a href="https://github.com/danielroe/nuxt-time/pull/228">#228</a></td>
</tr>
<tr>
<td>🟢 @a4vg</td>
<td>Mar 10, 2024, 10:52:41 PM</td>
<td>WIP</td>
</tr>
<tr>
<td>🟢 @mitjans</td>
<td></td>
<td><a href="https://github.com/danielroe/nuxt-time/pull/121">#121</a></td>
</tr>
</tbody>
</table>

**Comment by mitjans** [comment]
Hi! I would like to help with this although I don't quite understand the issue at hand.

Are you trying to minify/transpile the script injected with `useHead`? Is that even possible to do?

**Comment by danielroe** [comment]
Yes, exactly. We'd need to run esbuild/rollup on the script at build time so we minify the script that is injected via `useHead`.

(Apologies for the delay in replying!)

**Comment by mitjans** [comment]
How can that be achieved? Is adding the runtime directory to the Nuxt transpile option enough, like in #121?

**Comment by danielroe** [comment]
No, that doesn't have the same effect. To achieve it, you need to run esbuild/rollup on the script at build time and probably inject the minified script through a virtual module.

**Comment by rishi-raj-jain** [comment]
@danielroe Do you have a similar example of the same?

**Comment by danielroe** [comment]
I think we do something similar in https://github.com/nuxt-modules/color-mode.

**Comment by Vijaykv5** [comment]
/attempt #3

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clip4d8oh0006jo0f8gcjn44k/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Vijaykv5** [comment]
@danielroe This issue still persists right? May I can give a try?

**Comment by danielroe** [comment]
Go for it!

**Comment by a4vg** [comment]
/attempt #3

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clip4d8oh0006jo0f8gcjn44k/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
