### ISSUE TITLE
Uncaught ReferenceError: formatter is not defined

### ISSUE THREAD

**Issue by Luffyyy** [danielroe/nuxt-time#301]
### 🐛 The bug

Whenever using the module in any way, there's an error in the browser console "Uncaught ReferenceError: formatter is not defined". This happens in the given playground in the README on the latest Nuxt (3.14.159).

### 🛠️ To reproduce

https://stackblitz.com/github/danielroe/nuxt-time/tree/main/playground

### 🌈 Expected behaviour

No errors in the console

**Comment by ronenteva** [comment]
It seems to only happen with using `relative`

**Comment by jawnothin** [comment]
I put up a PR for this: https://github.com/danielroe/nuxt-time/pull/310
